#ifndef INTERFACESBOXADMIN_GLOBAL_H
#define INTERFACESBOXADMIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(INTERFACESBOXADMIN_LIBRARY)
#  define INTERFACESBOXADMINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define INTERFACESBOXADMINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // INTERFACESBOXADMIN_GLOBAL_H
